#!/bin/sh
echo GATEWAY_INTERFACE:    $GATEWAY_INTERFACE
echo GEMINI_DOCUMENT_ROOT: $GEMINI_DOCUMENT_ROOT
echo GEMINI_URL:           $GEMINI_URL
echo GEMINI_URL_PATH:      $GEMINI_URL_PATH
echo PATH_INFO:            $PATH_INFO
echo PATH_TRANSLATED:      $PATH_TRANSLATED
echo QUERY_STRING:         $QUERY_STRING
echo REMOTE_ADDR:          $REMOTE_ADDR
echo REMOTE_HOST:          $REMOTE_HOST
echo SERVER_NAME:          $SERVER_NAME
echo SERVER_PORT:          $SERVER_PORT
echo SERVER_PROTOCOL:      $SERVER_PROTOCOL
echo SERVER_SOFTWARE:      $SERVER_SOFTWARE
exit 0
